### ISSUE TITLE
/usr/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by joehillen** [commercialhaskell/intero#117]
Archlinux recently updated from ghc 7.10.3 to 8.0.1, and my stack environments seem to have had to switch from using system ghc to local.

`stack build` works fine, but intero in emacs fails. 

```
$ stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
$ stack ghci --with-ghc intero "--docker-run-args=--interactive=true --tty=false" --no-load --no-build --ghci-options -odir=/tmp/intero29680Fha --ghci-options -hidir=/tmp/intero29680Fha vault
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: vault
/usr/lib/ghc-7.10.3/settings: openFile: does not exist (No such file or directory)
```

**Comment by chrisdone** [comment]
Try `stack build intero` to rebuild intero with the new GHC version.

**Comment by joehillen** [comment]
That did it. Thanks

**Comment by shajra** [comment]
In my case, Intero is looking for /usr/lib/ghc/settings.  Since Stack can manage multiple installations of GHC just fine, I uninstalled my system-wide one.  But it seems that pulled away this settings file and broke Intero.  Would it be possible to have Intero completely use the GHC provided by Stack?  It's not the biggest deal.  I can have a system-wide GHC installed to keep Intero working.  But it does confuse things, because it means we're using two GHC installations for development work.

**Comment by chrisdone** [comment]
Intero is intended to work with the GHC version managed by Stack ideally. I think you can try some things to get rid of remnants of your global GHC:

    $ which ghc

Run this inside Emacs. If it succeeds, you haven't installed GHC properly. If it says no such file, you're good to proceed to the next step: run this in your project directory.

    $ stack exec ghc-pkg -- unregister intero --force

Check that `intero` is completely gone with `which intero` or `stack exec which intero`. Remove any. Now Emacs will automatically install intero with your Stack-managed GHC.

**Comment by shajra** [comment]
I tried everything you suggested above, and the problem persisted.

If you have a suggestion, I'm open.  But at this point I think the problem is ultimately with Stack, and not with Intero.  I don't know all the meta data under ~/.stack too intimately yet.  But I think when I originally did a "stack setup" command, it left some pointers to where I had ghc installed by Apt on my Debian box.  When I removed it, I guess this was as dangling reference.

Out of laziness, I blew away my ~/.stack and allowed it to rebuild from scratch, and this whole problem went away.

**Comment by PierreR** [comment]
FWIW I have had the exact same problem on `nixos` whenever I want to switch from a project that is using stack packages and other that  use packages from `nix` instead using the `shell-file option).

The second alternative is the only one that works for me whenever I have system dependencies (see https://github.com/commercialhaskell/stack/issues/2130).

I will try to only go along with the second option only and see if the problem is coming back.

That said, I am wondering if there isn't something fragile causing the issue so maybe it should be re-opened.

**Comment by greenrd** [comment]
For me, deleting the current snapshot and precompiled intero and ghc-paths packages was not enough, but when I also deleted the 8.0 stackage snapshot and did, in the global project:

```
stack exec -- ghc-pkg unregister --force syb
```

then rebuilt intero globally - and then in my project, updated the resolver version in stack.yaml - it finally worked.

I am still not sure exactly where the dirty paths are being picked up from, but it must be somewhere inside the snapshots.
