### ISSUE TITLE
error in process filter: process-get: Wrong type argument: processp, nil

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/intero#141]
I started getting this error after switching from [this Spacemacs layer](https://gist.github.com/dysinger/63b7cd03f77ac0125356051b23f47a37) to [this one](https://github.com/cydparser/spacemacs-intero), but switching back isn't fixing it. I get the message in the title when Intero starts, and the flycheck indicators never stop being '?'s. I'm not sure if this is actually an Intero bug, or if I somehow broke my Emacs setup.

From `*Messages*`:
```
Booted up intero!
error in process filter: process-get: Wrong type argument: processp, nil
error in process filter: Wrong type argument: processp, nil
```

I uploaded a backtrace from running `toggle-debug-on-error` and then `intero-restart`: [bt2.txt](https://github.com/commercialhaskell/intero/files/352963/bt2.txt). It has non-ASCII characters in it, so it confuses some text editors, but Emacs works fine.

**Comment by clojj** [comment]
I _think_ this is actually related to one or some of these very recent package-updates:

![screen shot 2016-07-07 at 22 48 24](https://cloud.githubusercontent.com/assets/4367963/16669324/27841a0a-4495-11e6-87ef-ffef1b507e69.png)

I use [this layer](https://github.com/cydparser/spacemacs-intero) too, but after upgrading packages in spacemacs, that same error message came up.

Downgrading all 7 packages fixed this for me.

Fiddling a bit with the package-manager, I think the cause is the most recent **flycheck** package, but I'm not sure about that...

**Comment by clojj** [comment]
I guess [**this**](https://github.com/flycheck/flycheck/issues/1005) should resolve it...

**Comment by chrisdone** [comment]
Might be caused by [this](https://github.com/flycheck/flycheck/pull/973/files) update to flycheck. Not sure...

**Comment by Blaisorblade** [comment]
I got this error (with normal Emacs) up to few minutes ago, did all upgrades (especially to intero and flycheck) and now things work, as predicted by @clojj (https://github.com/commercialhaskell/intero/issues/141#issuecomment-231207687).

**Comment by chrisdone** [comment]
Apparently this is fixed. @enolan, close when you're satisfied.

**Comment by enolan** [comment]
Fixed after update :) Thanks, @clojj @chrisdone @Blaisorblade.
