### ISSUE TITLE
Intero will accept intero executables built for the wrong GHC

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/intero#161]
I installed intero in the global project (that uses GHC-7.10.3 and lts-6.6). That makes sense for all projects using that snapshot, but not others — so for those projects, one must install a different `intero` version using `stack build`. I can do that by hand, but `(intero-installed-p)` doesn't detect the need (because `intero --version` doesn't report the GHC version this intero is for).

Hence, on a project using `ghc-7.8.4`, at intero startup I get by default:

```
[Intero] <- Intero 0.1.15 (GHC 7.10.3)
Type :intro and press enter for an introduction of the standard commands.

/Applications/ghc-7.8.4.app/Contents/lib/ghc-7.8.4/package.conf.d/package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not a ghc-pkg db file, wrong file magic number)
```

**Comment by chrisdone** [comment]
Installing Intero globally is user error. There is supposed to be one intero per GHC per LTS, by installing something globally you're disabled that stability.

**Comment by chrisdone** [comment]
For the benefit of future users I'll add some kind of way to detect whether the `intero` in the PATH is local or global.

**Comment by Blaisorblade** [comment]
Ah, so `stack build intero` is still fine, only install is the problem. Thanks for the patience with such errors of mine!

**Comment by chrisdone** [comment]
No worries, I did have it in the docs originally, but it [got moved here](https://github.com/commercialhaskell/intero/blob/master/TOOLING.md#installing). I still think auto-detection in Emacs would be beneficial if feasible! :+1:

**Comment by mgsloan** [comment]
One option would be to have a `--require-intero 0.1.15` flag when it gets run.  This'd avoid the overhead of invoking `intero --version`.

**Comment by Blaisorblade** [comment]
@msgloan Note that won't downgrade intero, because of commercialhaskell/stack#2373.

**Comment by mgsloan** [comment]
@Blaisorblade I cannot reproduce that issue.  Perhaps provide verbose logs / more repro?

**Comment by ntc2** [comment]
I just ran into this in a very convoluted way. I had not installed Intero globally intentionally, but I have a `.stack-work/install/<arch>/<lts>/<ghc version>/bin` dir on my path -- this way I can "uninstall" the corresponding binaries by changing my path, instead of having to go into `~/.local/bin` and deleting them -- and so after editing that project with Intero there was an `intero` executable on my path! This in turn caused the OPs problem when using Intero to edit Haskell files not associated with a project, after I changed my `~/.stack/global-project/stack.yaml` resolver from an LTS (GHC 7.10.3) to a nightly (GHC 8.0.1).

So, here's another vote for making Intero work correctly when there's an incompatible `intero` executable on the PATH. Or at least, detecting this case and yelling at the user, perhaps suggesting the `stack build intero` locally workaround.

**Comment by Blaisorblade** [comment]
> There is supposed to be one intero per GHC per LTS, by installing something globally you're disabled that stability.

Note: right now, there's one intero per project. I could have 45 projects with the same LTS, yet I'd need building intero for each one. Not sure if intero can be shared across similar LTSs—say 6.0 and 6.1?
Also, don't we just need one intero per GHC? If so, it'd be great to install intero-7.8.4, intero-7.10.3 and intero-8.0.1, on demand.

**Comment by ntc2** [comment]
This just bit me again, in the same way. "Fool me once, shame on you, fool me twice, shame on me". I  guess I better go buy some ginkgo.

**Comment by mgsloan** [comment]
@ntc2 I think it is intero's responsibility to eliminate such failure cases :)  Soon I hope everything will just work all the time!

**Comment by chrisdone** [comment]
This doesn't happen anymore.
