### ISSUE TITLE
Make application of suggested refactorings into an intero process feature?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#190]
I saw that @acowley added a really cool feature for applying GHC's redundant constraint warnings - https://github.com/commercialhaskell/intero/pull/184 .  See also #188

This made me recall one of the things I really like about haskell-ide-engine's design philosophy, which is to attempt to move as much complexity into the shared component (the `intero` process), avoiding complexity in the editor integrations.  So, in other words, the idea is to put the logic of computing the text updates in intero itself.  Intero would provide a list of suggested modifications.   These might reference the position in the error message, possibly additional description, and a list of text substitutions.

One difficulty is applying these refactorings when the source code has already been changed.  There, writing it in emacs potentially has an advantage, as it has the current buffer and potentially even knows what has changed.  A few different ways to address this:

1) Expect the editor to track changes in source locations.  Not sure how feasible this is.  The idea is that we'd be able to "snapshot" the state of the code when it was last compiled, and track how the positions have changed since then.  This allows us to attempt to use locations derived from the last compilation.

2) Send over the current buffer contents, and use this as an input when computing the text substitutions for the refactoring.

3) Disallow applying refactorings to a modified buffer - require accurate source locations.  It'd be nice to have an "apply all suggestions" option, which lists the things that will be changed (ideally allowing some to be disabled).  If such an "apply all" did not exist, then a recompile would need to accompany every refactoring.

**Comment by acowley** [comment]
I agreed with this sentiment in #188, but I'll play devil's advocate here because I'm already of two minds on the issue. (Pre-apology: I am going to unfairly characterize things here to avoid mincing words)

- I think this was a fatal mistake of `haskell-ide-engine`. It's a project that seemed to me like bureaucracy and architecture astronautics first, execution last. The appeal of doing things in emacs is that it is easy to do them there. I don't need to be sold on the fact that ideally these things would be done in Haskell, but to sweep under the rug the reality that it is harder to do so is the first step on the road to perdition. To be concrete, adding things in emacs is a live, iterative, convergent process. What is the work flow when more of the logic is moved into the Haskell code?

- I am not particularly swayed by the shared component angle, as catering to all needs is another way to hamstring yourself. Making development more difficult to appease potential non-emacs users is a risky strategy.

- Given that Intero exists distinctly outside of GHC itself and aims to co-exist with multiple GHC versions, flexibility will always be essential. If a tiny wobble in GHC's behavior or output causes a problem in Intero that is anything but trivial to fix, Intero stumbles.

**Summary** Let's pursue moving parsing into the Intero process incrementally, and leave the emacs escape hatch open. Regarding the stale buffer questions: a triumph of Intero's emacs code is demonstrating that a simple solution is probably good enough. Let's try things out without insisting that a design be fully sorted first. We'll probably get it wrong.

**Comment by mgsloan** [comment]
I agree with the idea of implementing something like this incrementally.  It's also certainly true that HIE did a lot of design upfront, which is one reason I'm keen to capitalize in the ideas.

**Comment by acowley** [comment]
Point well taken about benefiting from the work they put in.

**Comment by purcell** [comment]
There's possible overlap here with plans to add "error fixers" to `flycheck`: https://github.com/flycheck/flycheck/issues/530#issuecomment-235192405

I suggested that feature a while ago and it's starting to gather interest and activity.

Since intero integrates nicely with flycheck, I think it might make sense to build any work here on top of whatever the flycheck solution ends up looking like.

**Comment by chrisdone** [comment]
@purcell If that ends up being pretty good and merged, we can consider it. :+1: For the time being we're still exploring the design space.


---

Unrelatedly, the participants in this issue are perfectly angled with respect to the camera:

<img width="152" alt="screenshot 2016-07-26 12 06 37" src="https://cloud.githubusercontent.com/assets/11019/17134235/bded0f40-5329-11e6-9512-47830fc8d6a2.png">

It's the simple things in life.

**Comment by acowley** [comment]
That's great! I was doing a little rust coding a few days ago and started toying with the idea of porting intero-mode just to get the suggested fixes tooling. I'm really impressed with how well it works for GHC.

**Comment by tonyday567** [comment]
I'm now very cautious about the concept of structured code as the right data form for refactoring.  Refactoring is editing text, first and foremost.

If you go all out with structured data (like haskell-ide-engine seemed to), then text-based, external components such as flycheck look inferior - monolithic, closed-world design here we come.  

But I'm seeing a nice haskell tool ecosystem developing around flycheck.  hlint-refactor and intero are now both making flycheck annotations and both offering refactorings at point, and text is the medium of the messaging.  I'd like to see prettifiers like stylish-haskell and hindent do the same.

Whether it's easier to code up in the intero executable or in elisp might depend on the specifics of the  transformation from text to structured code.  If all the extra bits left over (the style annotations say) are critical, and you have to also feed them into intero to get back sensible results, then you're back to munging text. Of course, I prefer munging text in haskell, but that's a different thing to preferring munging text via always converting it to structured code + style annotations.
