### ISSUE TITLE
Select all targets at startup?

### ISSUE THREAD

**Issue by afcowie** [commercialhaskell/intero#195]
It's a bit jarring to load up a test suite and have Test.Hspec showing an error. Oh, I eventually realize, I need to tell Intero that I want the test suite to be the active target. Ok, what's the syntax for that again? Then navigation doesn't work to the library part of the package. Huh? Oh, I need to select the lib target too.

So now I remember that when I start Emacs I have to go through the menus to get to Intero targets, to then select all the cabal targets. Which is a bit tedious to do every time I [re]start Emacs.

Is there a way to get Intero to just enable all the available targets in a project at startup? As it seems prerequisite to tag navigation working it seems like a sensible default to suggest.

Thanks either way,

AfC

**Comment by chrisdone** [comment]
I agree it's not ideal. We could perhaps enable all targets in a cabal file. If we enable all packages in a stack project, it has potential to fail hard when on a big project (one of our clients at FP Complete had this issue). 

The issue is really how to communicate to users that a problem with compilation is happening because they have conflicting or not enough targets selected. But enabling everything in the .cabal file might be a reasonable approach.

**Comment by afcowie** [comment]
@chrisdone huh. It occurs to me there _is_ the `buildable: False` flag that someone could add to their .cabal file if they wanted to disable a target. Maybe we could key off that.

**Comment by mgsloan** [comment]
Setting the targets to `--test --bench` ought to do the trick.

**Comment by bjchambers** [comment]
I think this would also solve my earlier question (https://github.com/commercialhaskell/intero/issues/55).

I tired setting intero-targets using `.dir-locals.el` but didn't have any luck. If there was some way to set the targets (or the initial, default targets) for a directory (and its sub-directories) that might solve the problem with large projects.

**Comment by mgsloan** [comment]
Yeah, targets syntax supports directories.  Does it work for you?

**Comment by bjchambers** [comment]
I'm not sure I understand. I was suggesting that if there was a way to configure intero-targets for all files in a project using a file like .dir-locals.el, then it would address both my earlier question and this question without needing to use all the available targets.

For issue #55 and this one, we could configure the appropriate targets (maybe all of them). It also seems to address the case of all targets being too many, since you can just leave out the targets you don't want included.

**Comment by bjchambers** [comment]
Actually, I figured out I was just using .dir-locals.el incorrectly. I was trying something like:

```
((intero-mode . ((intero-targets . "Foo:lib Foo:tests"))))
```

But this seems to work:

```
((haskell-mode . ((eval . (intero-targets "Foo:lib Foo:tests")))))
```

Something similar may address the original question here -- just create a `.dir-locals.el` that configures the appropriate targets for the project.

**Comment by ghorn** [comment]
```((haskell-mode . ((eval . (intero-targets "target1 target2 target3")))))```
doesn't work for me. It gives:

```
Please type y, n, or !: y
File local-variables error: (wrong-number-of-arguments #[nil "r\304\305!q\210)\306 \211\203\307\310\311\312
\"\"\202'\313\314\315\316\211\211\211	&\317\320#\321 \210\322\305p#+\207" [intero-targets old-targets available-targets targets intero-buffer backend intero-get-targets intero-multiswitch "Targets:" mapcar #[(target) "\302\303\304	\235\257\207" [target old-targets :key :title :default] 7] split-string read-from-minibuffer "Targets: " nil " " t intero-destroy intero-get-worker-create] 9 ("/home/greghorn/.emacs.d/elpa/intero-20160812.350/intero.elc" . 9780) nil] 1)
Booting up intero ...
Booted up intero!
```

**Comment by bjchambers** [comment]
Yeah. It looks like I was getting the same error. I thought `intero-targets` could be used to set the targets but it only works in interactive mode.

Looking at the source I was able to come up with this (which seems to be the part of `intero-targets` does after getting the targets, and this seems to work. 

```
((haskell-mode
  . ((eval . (with-current-buffer (intero-buffer 'backend)
	       (intero-destroy)
	       (intero-get-worker-create 'backend
					 '("target1" "target2" "target3")
					 (current-buffer)))))))

```

**Comment by ghorn** [comment]
That gives me

```
The following target packages were not found: target1, target2, target3
```

**Comment by bjchambers** [comment]
Hmm. If you run `intero-targets` and pass `target1 target2 target3` does it that work? The list of targets should be the same as the targets specified for `intero-targets`.

**Comment by ghorn** [comment]
I confirm it does work running `intero-targets` `target1 target2 target3` manually.

**Comment by ghorn** [comment]
The targets are in subdirectories, if that makes a difference.

**Comment by ghorn** [comment]
To be clear
```
.
├── stack.yaml
├── some_subdir
│   ├── target1
│   ├── target2
│   ├── target3
```

**Comment by bjchambers** [comment]
If you do `stack ide packages` it should list the names of packages. Each target should be something like `Package:lib` for the library in `Package/Package.cabal`, or `Package:tests` if you have `Test-Suite: tests` in your `Package/Package.cabal` file.

**Comment by Blaisorblade** [comment]
Ideally, `intero` would figure out that tests are tests from `hs-source-dirs` in the cabal project. Or delegate that to `stack` somehow.

For now, I'm using https://github.com/commercialhaskell/intero/issues/195#issuecomment-239634535, using as target `stack:lib stack:stack-test`. That's better than using `--test --bench`, since targets are not required to have compatible dependencies. In comparison, one can omit `stack:lib` for tests that don't depend on the library component.

Then I tried setting intero-targets to `stack stack:stack-test`, but that failed:
```
Error parsing targets: Overlapping targets provided for package stack: ["stack","stack:stack-test"]
```
Finally, I succeeded by setting intero-targets to `stack:lib stack:stack-test`.

> If you do stack ide packages it should list the names of packages. Each target should be something like Package:lib for the library in Package/Package.cabal, or Package:tests if you have Test-Suite: tests in your Package/Package.cabal file.

Nope, at least on stack itself. It only lists packages, not components/targets—packages map to 
The docs seemed to suggest I should use load-targets, but that requires a target and list its files, after building/running the target.

```
$ stack ide packages
stack
$ stack ide load-targets stack
[... Compiles Stack... why?]
[lists source files, including generated ones]
$ stack ide load-targets stack:stack-test
[... Compiles and runs Stack test-suite... why?]
[lists source files, including generated ones]
```

**Comment by agrafix** [comment]
How about supporting a `.intero` file next to the `stack.yaml` to indicate which targets should be used?

**Comment by Blaisorblade** [comment]
Re `.intero`: `.dir-locals.el` should suffice, but we probably something more integrated than the above code. And then we'd also want some sensible defaults as discussed.

**Comment by bjchambers** [comment]
Yeah -- `.dir-locals.el` seems like a reasonable approach to allow a directory to configure a local variable (and plays nicely with other modules like projectile). But, the fact that the `.dir-local.el` is currently interacting with low-level functionality to set the `intero-targets` and restart the buffer seems ugly.

Would it make sense for their to be a variable like "init-intero-targets" that, if set, serve as the `intero-targets` for a buffer? This would allow the `.dir-locals.el` to be:
```
((haskell-mode . (init-intero-targets . "package:lib package:test"))))
```

**Comment by chrisdone** [comment]
`.dir-locals.el` seems like the already standard way to achieve this. I'm fine with a variable to set the default targets.

**Proposal**:

Intero will apply this variable to a `.dir-locals.el` file in the same directory as your `.stack.yaml` once you choose your targets the first time, it can _just remember them_ and write them to that file. This saves anyone having to know that the `.dir-locals.el` is even a thing or the syntax.

**Comment by Toxaris** [comment]
Shouldn't the set of targets be per source file, not per project?

**Comment by Blaisorblade** [comment]
IIUC, a different set of targets forces the intero process to be restarted (not sure if that's easy to change). But one could in principle have an intero process per component and map each source to its component (assuming again all source files belong to exactly one target), and still achieve what @Toxaris proposes.

As long as the set of targets is per project, loading together all enabled components would usually work (technically, different components might not be loadable together, but not sure the exceptions matter, or that they even work with Stack).

Assuming components load together, that should guarantee that "we can build the project" leads to "intero shows no error", but not viceversa (intero won't notice if I use testing-only libraries in my library component).

**Comment by Blaisorblade** [comment]
BTW I'm using the `.dir-locals.el` trick, but it seems to have stopped working on some versions...

**Comment by Blaisorblade** [comment]
Here's what happens with the `.dir-locals.el` trick:
- when you first load a fail, `intero` tries to interpret the targets in `~/.stack/global`, hence fails. This is fixed by reloading the file.
- the settings reload intero for every opened file in the affected directories (when it's opened).

So, right now setting intero-targets by hand after Emacs startup works better. @bjchambers since you came up with the original incantation, do you happen to have a fixed version?

**Comment by unhammer** [comment]
Could we also have some examples on `M-x intero-targets`? I only found out how to set it correctly by reading through this long issue …

**Comment by saurabhnanda** [comment]
Just chiming-in to say that I had the same experience as @unhammer Is it possible to have `M-x intero-list-targets`?

**Comment by purcell** [comment]
I've made some changes around this in 9761b71. Now when you call `intero-targets` interactively, you'll be asked whether to save the settings in directory-locals for future use. I'd be keen to hear whether that does the trick for people here.

(@saurabhnanda Regarding listing targets, you can just use `M-x intero-targets`, then cancel with `C-c C-k` or `C-g`.)

**Comment by saurabhnanda** [comment]
> (@saurabhnanda Regarding listing targets, you can just use M-x intero-targets, then cancel with C-c C-k or C-g.)

@purcell is this for your new commit, or for existing Intero. Because I tried `C-C C-k` and it said "undefined", and `C-g` simply cancelled the minibuffer for `intero-targets`

**Comment by purcell** [comment]
@saurabhnanda I meant this sequence:
- `M-x intero-targets`
- _now you can see a list of the targets_
- `C-g` or `C-c C-k` to cancel

**Comment by koterpillar** [comment]
The variable doesn't seem to take any effect. I've set the targets from the list and saved them. Now when I open a file in that project again, I get asked: "The local variables list in ... contains values that might not be safe. Do you want to apply it?" Even though I say `y`, the targets are still not loaded (verified by opening a test module - the test dependencies are not found).

**Comment by purcell** [comment]
@koterpillar It works for me locally right now, but I have seen this inconsistent behaviour too, I feel like there may be an edge case in which a local `intero-targets` variable does not necessarily cause the started `intero` backend process to use those settings. I'll have a think about what might be going wrong.

**Comment by saurabhnanda** [comment]
@purcell finally tried it today. Works like a charm :) 👍

**Comment by yogsototh** [comment]
For me intero created the `.dir-locals.el` with the correct list of targets. Unfortunately, I don't know why, but if I restart emacs it is not taken into account. I still need to manually add the targets in emacs.

**Comment by Blaisorblade** [comment]
@yogsototh I’m no expert, but does Emacs *ask you* if you accept those variables? I assume not, since you don’t mention it. What happens if you refresh the files with `M-x revert-buffer`?

IIRC I have to accept them as safe, because `.dir-locals.el` can be exploited by attackers to run commands. For *me*, IIRC, Emacs just asks when loading a file under the scope of `.dir-locals.el`, or when reloading it with `M-x revert-buffer`, and allows whitelisting settings, but I assume this behavior can be customized by your Emacs config. Also not sure how this interacts with Emacs session saving.

If this isn’t the answer, maybe try troubleshooting procedures by, say, booting without Emacs customizations/sessions, or to find people with more clue maybe visit https://emacs.stackexchange.com/ or your favorite resource might help.

References:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Safe-File-Variables.html#Safe-File-Variables
https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

**Comment by yogsototh** [comment]
So I get the warning, I save it as safe even for future session. But the current session as well as future one I still need to add the inters-targets manually. I'm not sure this is an intero problem and as more to do with my Emacs configuration. So I'll try to find a way to make it work for me and I'll give the solution if I find one. Thanks for your help.

**Comment by Blaisorblade** [comment]
I sometimes need to `intero-restart` explicitly after changing targets, even when it makes no sense for a user. If *that* helps that’s intero’s fault.

**Comment by purcell** [comment]
Yep, this still isn't working right. I helped with the directory local variables change initially, and I think that the intero process sometimes gets started from a buffer in which the targets variable has not been set buffer-locally. Haven't figured it out yet, but hope to get to the bottom of it sooner or later.

**Comment by jeremyjh** [comment]
@yogsototh did you figure this out? I have the exact same issue; I get prompted to trust `.dir-locals.el` and I do, but intero targets are not set until I do it manually.

**Comment by yogsototh** [comment]
@jeremyjh no, I changed how I think I switched to use stack with docker and since then my configuration appear to be taken into account correctly. So I'm not able to reproduce the issue currently.

**Comment by jeremyjh** [comment]
@purcell You are right! I was on the 20180605 build - I just installed current melpa and the problem is resolved. Sorry for the noise.
