### ISSUE TITLE
Intero writing files on every text change, not waiting for user to save

### ISSUE THREAD

**Issue by afcowie** [commercialhaskell/intero#196]
(so I'm using evil-mode, because that's what Spacemacs enables. Maybe that's to blame)

Some of my existing Haskell tooling was freaking out, so I set up some inotify watches to see what was going on and quite to my astonishment, every time I make a textual change to one of my Haskell source files _it's writing the file to disk_. It's not waiting for me to save the file! Is that expected?

I realize that git saves the day at a course grain if something isn't right, but is this expected behaviour on the part of Intero (Emacs?). Numerous writes to disk are happening every few keystrokes and seems likely to cause excessive wear on the storage medium. 

If it _is_ expected behaviour, then it should be marking the buffer as saved / unmodified / whatever, right? The `*` marker is still there even though it has saved the file to disk already.

```shell
inotifywait -r -m .
```
if you want to observe this for yourself.

**Comment by chrisdone** [comment]
Open issue here: #148

It's expected and part of how flycheck works (you write the buffer contents to a file and then run your checker on it). You have to save a file for GHC to load it in and check it (although it would be nice if GHC could more easily load a module in as a string directly).

What you can do is change your flycheck settings so that it only checks when you save the file:

``` lisp
(setq flycheck-check-syntax-automatically '(save))
```

The part that is not ideal is that we mark the buffer as not saved, which is to avoid Emacs prompting that something changed while you're typing. This screws with magit a bit, and things like that. Hence the open issue.
