### ISSUE TITLE
Intero falls over for silly project structure.

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/intero#211]
I have two packages I'm working on, and have them as subfolders of a project that acts as the playground, exercise area for both.

E.g.

```
Playground
|-- PkgA
'-- PkgB
```

Playground simply includes `src`, `PkgA/src` and `PkgB/src`. However both packages sport their own `stack.yaml`. Editing a file in either Pkg, results in intero trying to start a session for that package. In this case PkgB depends on PkgA and intero topples over with ghci trying, but failing to locate PkgA, when editing a file in PkgB.

**Comment by chrisdone** [comment]
If they use eachother, why do you have two separate stack.yaml files?

**Comment by mgsloan** [comment]
I've also encountered this situation.  One case where it occurs is if you have a submodule which contains a stack.yaml.  The resolution doesn't seem clear, though.  One option is to instead default to the outermost `stack.yaml`, but this is inconsistent with the normal CLI behavior.  Perhaps the circumstance where there are multiple `stack.yaml` files in parent directories should be pointed out to the user, and they can select?

**Comment by angerman** [comment]
As @mgsloan it also happens if you have submodules that happen to have `stack.yaml` files. 
My current solution is to look for all `**/stack.yaml` and rename them to `stack.yaml.bck`.
That is a bit annoying but works for now.

**Comment by chrisdone** [comment]
We could provide a `M-x intero-root` or `M-x intero-stack-yaml` command which presents a choice of the detected `.yaml` files. When running any stack command, it will pass `--stack-yaml` (or w/e it was) to the executable, or set it as an environment variable in local buffers. Then some message could say "Use `M-x intero-root` to pick which one."

**Comment by angerman** [comment]
If we can inhibit intero from trying to start a second session, that would solve all my issues.

E.g. "You already have an intero session running for a project higher up in the hierarchy, however, the file you are editing belongs to project with a separate `stack.yaml`. Do you want to start a separate intero session? Y/N"

**Comment by angerman** [comment]
I guess the simples would be: *if* an intero session is already running in a higher up in the fs hierarchy, do *not* start a new intero session. If one want's a separate session `C-u M-x intero-repl`?

**Comment by ntc2** [comment]
I would like something like the `intero-root` that @chrisdone suggests, or even a `intero-stack-yaml-blacklist`.

I frequently have the problem that my project has a top level `stack.yaml` and several submodules that also have `stack.yaml`, and Intero tries to use the submodule `stack.yaml`s when I edit submodule files. What I want is for Intero to only use the top level `stack.yaml`. My usual work around is to delete the submodule `stack.yaml` files and try to remember not to commit those deletions, but this is an annoying workaround because it produces a lot of `git status` noise.

Suggestion: change the title of this issue to something more descriptive, e.g. "Intero doesn't work well for projects with multiple `stack.yaml` files".
