### ISSUE TITLE
Intero automatically saves buffer when flychecking, which breaks other modes.

### ISSUE THREAD

**Issue by ntc2** [commercialhaskell/intero#242]
The `intero-check` calls `intero-save-silently` to save the buffer. This leads to automatic buffer saves in the default flycheck configuration where `idle-change` and `new-line` are part of `flycheck-check-syntax-automatically`. This automatic saving causes at least two problems:

1. other modes that are triggered by saves don't work correctly. E.g., this breaks [GitGutter](https://github.com/syohex/emacs-git-gutter). Note that `C-x C-s` runs `save-buffer` which is "smart" and only saves the buffer if modified, so you can't simply do an extra `C-x C-s` to work around this.

2. you lose the visual indication of whether you have any unsaved changes or not. Not really sure why this is a big deal, but I'm used to having this feedback since forever in Emacs.

Related, closed issues: #148, #196.

Work around: put `(setq flycheck-check-syntax-automatically '(mode-enabled save))` in your `~/.emacs`. For larger projects, also doing `(setq haskell-tags-on-save nil)` is useful, since that's set by default in Intero, but isn't triggered by `intero-save-silently`, so you don't notice how slow it is until you disable idle Flychecking.

**Comment by mgsloan** [comment]
Hey Nathan!  Thanks for looking into the details of what's going on there.  I've also seen this mess up magit, such that after checkout, I still have the old buffer state, or something along those lines.

**Comment by chrisdone** [comment]
The file is actually saved, so you don't have any unsaved changes when using intero with flycheck.

The problematic part of the current implementation is that in order to save the buffer while editing, we need to disable save hooks, otherwise it'll run all sorts of hooks while you're working.

The underlying problem is that making a copy of the file and checking that would require file path munging in various places, but it looks like it may be the only solid solution.

**Comment by purcell** [comment]
Yes, big +1 for this issue -- the current implementation breaks a number of things for me, from before-save hooks (stylish, hindent) to the simple expectation that I can control when and if to save the file.

I'm happy to help with the temp-file-copying solution, because I agree that it is the only viable solution.

**Comment by purcell** [comment]
My pull request #248 eliminates the silent saving, and therefore this issue.
