### ISSUE TITLE
Autocompletion not working in REPL

### ISSUE THREAD

**Issue by mtesseract** [commercialhaskell/intero#245]
Hi,

unless I am overlooking something obvious, there is no tab-autocompletion in the Intero REPL.
It would be very nice to have, though. :-)

Thanks,
Moritz

**Comment by chrisdone** [comment]
I recently pushed support so that company-mode is activated in the REPL. Have you tried a recent version?

**Comment by crocket** [comment]
I installed the latest version from melpa today, but tab autocompletion doesn't work.
When I press TAB, a lot of spaces are inserted into REPL.

**Comment by mtesseract** [comment]
Sorry for the delay.

The melpa version intero-20160825.656 didn't provide me with tab-completion in the REPL (it simply inserts whitespaces).

I have just directed my Emacs (24.5.1) to use intero's git master version, it has shown the same behaviour.
C-h k TAB tells me:

TAB (translated from <tab>) runs the command indent-for-tab-command,
which is an interactive compiled Lisp function in `indent.el'.

[I have the following snippet in my .emacs for using intero's master:
(add-to-list 'load-path "~/.emacs.d/intero/elisp/") ;; This is the master branch
(require 'intero)
(add-hook 'haskell-mode-hook 'intero-mode)
]

Am I doing anything wrong here? Can I help debugging this?

**Comment by ntc2** [comment]
Same problem: `company-mode` completions do work in the REPL, but **plain old TAB completions**, like you get with terminal GHCi, **do not work**.

Running `C-h k TAB` in the REPL tells me TAB is bound to `indent-for-tab-command`. I tried inserting a raw TAB with `C-q TAB`, but that doesn't work either ?!

**Comment by TimoFreiberg** [comment]
I assume I have the same problem: I can use company mode for completions, but the completions seem to be pure text-based. I don't get suggestions based on imported modules, for example.

The old haskell-interactive mode shows completion suggestions from all imported packages, the entire Prelude, etc.
I miss this in Intero

**Comment by pashosh** [comment]
i miss it also :-)

**Comment by purcell** [comment]
@TimoFreiberg Not the same issue, so it might be a separate bug, or a point of confusion. You'll only see company completions for imported modules in the Intero REPL when you've successfully loaded a Haskell file.

@pashosh, @ntc2, @crocket and @mtesseract:

Regarding `TAB` completion, before we assume that something is broken in `intero`, let's back up and start with how `TAB` is supposed to work in Emacs: when you hit `TAB` and trigger `indent-for-tab-command`, the behaviour depends on what you've set the `tab-always-indent` variable to. See the docs for that var, but in general, you will want to customise that to `'complete` if you like `TAB` completion. This way, `TAB` will ask the current mode to adjust the indentation, and then _only if the indentation didn't change_, it will trigger `completion-at-point`.

You can see that any mode with variable/"bouncing" indentation (Python, *cough* Haskell) will not reliably trigger completion with this scheme, so it's worth getting in the habit of hitting `C-M-i` to explicitly trigger `completion-at-point`. (The trouble with this is that `intero` didn't have its own `completion-at-point` function: I've just [changed that](https://github.com/commercialhaskell/intero/commit/3aa01113913c46855f402c09dff95322f489c3c0), so `C-M-i` away!)

In the meantime, company completion is also working fine in the REPL, so I'll close this issue now.
Further, we could change the indentation behaviour in `intero-repl-mode` so that it does not simply insert spaces in many cases where you might hit `TAB`, and that would then cause the above behaviour to drop through to completion more often. But the main point is that you can't expect `TAB` to magically do the right thing in every circumstance anyway, so that wouldn't be a 100% solution.

**Comment by ntc2** [comment]
@purcell, thanks for adding a `completion-at-point` function. I haven't tried it yet, but it sounds like an improvement.

Re the tab completion in the repl/GHCi issue that I (and perhaps @TimoFreiberg?) are talking about, I mean that I'd like access to the built-in GHCi tab completion that I get when I run GHCi in a terminal, outside of Emacs. I.e. a pass through mode where GHCi treats `TAB` in it's native way. I agree this is not how Emacs treats tabs in source code editing modes, but since GHCi already has great built-in tab completion, why not just use it?

**Comment by KarlFish** [comment]
@ntc2 Checkout https://github.com/commercialhaskell/intero/pull/454 for a more native tab complete experience in the repl
