### ISSUE TITLE
Inconsistent output of :loc-at

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/intero#260]
```haskell
data User =
  User {_userId :: Int
       ,_userFirstName :: String
       ,_userLastName :: String}
  deriving (Generic,ToJSON, FromJSON )
```
```
:loc-at /home/rik/haskell/projects/api/src/Lib.hs 21 21 21 27 ToJSON
aeson-0.11.2.1:Data.Aeson.Types.Class
```
```
:loc-at /home/rik/haskell/projects/api/src/Lib.hs 21 29 21 37 FromJSON
/home/rik/haskell/projects/api/src/Lib.hs:(21,29)-(21,37)
```
So `FromJSON` refers to file itself and `ToJSON` refers package name en module name of Aeson.

**Comment by Blaisorblade** [comment]
FWIW Do you have a minimal complete example where this problem still happens?

**Comment by rikvdkleij** [comment]
@Blaisorblade 
See https://gist.github.com/rikvdkleij/f71cbf1e7f600530419878015af7e8c6

Thanks!

**Comment by Blaisorblade** [comment]
Thanks, but can you reproduce this error there? I can't, even after adding the Deriving line. I specified "where this problem still happens?" because my bet is this depends on other content of the file. Say, maybe there's some other explicit FromJSON instance confusing intero, or whatever. This might take a nontrivial amount of work (you might end up needing to "bisect" your source), so before that a simpler question: does C-c C-i get similarly confused?

Ultimately intero just queries the GHC API (https://github.com/commercialhaskell/intero/blob/897cb329ef08728642346530a668211120e7df4a/src/InteractiveUI.hs#L1786-L1808), that's why I expect these issues can cause erroneous information, though they shouldn't.

```
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}

module LocAt where

import Data.Aeson
import Data.Text
import GHC.Generics

data User =
  User {_userId :: Int
       ,_userFirstName :: Text
       ,_userLastName :: Text}
  deriving (Generic, ToJSON, FromJSON)
```

Here's my failed reproduction attempt:
```
$ stack ghci --with-ghc=intero
Prelude> :load LocAt.hs
[1 of 1] Compiling LocAt            ( LocAt.hs, interpreted )
Ok, modules loaded: LocAt.
Collecting type info for 1 module(s) ...
*LocAt> :loc-at LocAt.hs 14 22 14 27 ToJSON
aeson-0.11.2.0:Data.Aeson.Types.Class
*LocAt> :loc-at LocAt.hs 14 30 14 37 FromJSON
aeson-0.11.2.0:Data.Aeson.Types.Class
```

BTW, that `stack ghci` used the global project, that luckily did have some aeson version available.

BTW I'm just triaging this report, hoping somebody later can look into this or escalate it to GHC.

**Comment by rikvdkleij** [comment]
Yes, I can still reproduce the issue.

Did you put the right location columns/rows in the command?

I have put the complete module code in the gist.

**Comment by Blaisorblade** [comment]
Thanks for putting a more complete example. First of all: `C-c C-i` gives correct results, while the results for `:loc-at` depend on the exact range, and I'm now confused on which range one should use. `:loc-at` gives some valid-looking output even when I feed it utter nonsense, and the docs are ambiguous, so I can't tell any more.

To me the question now is: when `:loc-at` expects an end column, is that the last column of the string (as I think the help suggests) or the first position afterwards (as you're doing, and as most range APIs do)? The help for `:loc-at` isn't very clear.

```
*LocAt> :loc-at

<no location info>: Expected a span: "<module-name/filepath>" <start line> <start column> <end line> <end column> "<sample string>"
*LocAt> :help
...
   :loc-at <loc>               return the location of the identifier at <loc> of format:
                               <filename> <line> <col> <end-line> <end-col> <text>
                               text is used for when the span is out of date
...
```

Why do I ask? Because with your code one I get these results:

```
*LocAt> :loc-at LocAt.hs 14 37 14 45 FromJSON
LocAt.hs:(14,37)-(14,45)
*LocAt> :loc-at LocAt.hs 14 37 14 44 FromJSON
aeson-0.11.2.0:Data.Aeson.Types.Class
```

Seeing that, I thought "ah OK, the end column must be the last character". Then I wondered why in the other usage (from ToJSON) there isn't a problem, and it turns out the API doesn't do much validation:

```
*LocAt> :loc-at LocAt.hs 14 0 14 17 ToJSON
aeson-0.11.2.0:Data.Aeson.Types.Class
*LocAt> :loc-at LocAt.hs 14 0 14 17 ToJSO
Couldn't resolve to any modules.
```

The first attempt is what you did, the second looks like the intended usage to me, the third is garbage, shows there isn't enough validation and calls the second in question.

**Comment by Blaisorblade** [comment]
@chrisdone TL;DR. Does `:loc-at` consider the end column as included or excluded?

**Comment by rikvdkleij** [comment]
@Blaisorblade Thanks for your investigation!

Some time ago I came to the conclusion it was excluded. For most cases that works but I'm now confused...

**Comment by rikvdkleij** [comment]
@Blaisorblade @chrisdone 
I noticed that using the `loc-at` API with end column included, the inconsistency in results is gone.

What's left is improving documentation and validation of the input.

**Comment by chrisdone** [comment]
Looks like this cleared up while I was on vacation. Thanks @Blaisorblade!

A PR for documentation improvement would be welcome!

**Comment by rikvdkleij** [comment]
I found the inconsistency:
For identifiers defined inside functions it has to be used with end column excluded.

**Comment by Blaisorblade** [comment]
... Does `C-c C-i` deal with that somehow, or are you using some other frontend anyway? Just confirmed you're using `intero` in your own plugin (per comments in rikvdkleij/intellij-haskell@b9c77924a07d22162e931590d0cf9d464a8373f7).

**Comment by rikvdkleij** [comment]
Yes, I'm using my own IntelliJ plugin which is using Intero. I did not yet pushed latest changes.

I will create minimal example this weekend.

Btw, I'm very pleased with Stack and Intero.

**Comment by rikvdkleij** [comment]
@Blaisorblade 
Example:
https://gist.github.com/rikvdkleij/504ec9dbb34842d6d5f5bdb95017b752
