### ISSUE TITLE
intero should stay out of the way when it's not wanted

### ISSUE THREAD

**Issue by anderspapitto** [commercialhaskell/intero#319]
I'm working on a project that doesn't have a stack.yaml (because I cloned it just to contribute a quick fix upstream - so I don't care about syntax highlighting or flycheck or anything, I just want to get in and make my fix and be done).

This causes intero to hang when I open the project, because it automatically tries to install a bunch of stuff. To fix this, I put a stack.yaml in $HOME/ with `use-system-ghc: true`, so that intero won't try to do this when I open up random .hs files. That works (though it's a hack and ideally I shouldn't have to do it).

However, now a buffer repeatedly pops up roughly once a second with the following error message.

```
Warning (intero): Couldn't get the Stack project root.

This can be caused by a syntax error in your stack.yaml file. Check that out.

Otherwise, please report this as a bug!
```

**Comment by chrisdone** [comment]
Hi Anders. What does this say in the shell?
```
Chriss-MacBook-Pro:~ chris$ stack path --project-root --verbosity silent
/Users/chris/.stack/global
```

**Comment by anderspapitto** [comment]
In the first case I described (no stack.yaml to be found anywhere) it returns

```
/home/anders/.stack/global-project
```

In the second case (when I put a stack.yaml in $HOME to try to prevent it from installing intero automatically), that command gives

```
/home/anders
```

**Comment by chrisdone** [comment]
So I reproduced this, it's because you're introducing a parse error:

```
Chriss-MacBook-Pro:~ chris$ cat stack.yaml
use-system-ghc: true
Chriss-MacBook-Pro:~ chris$ stack path --project-root --verbosity silent
Could not parse '/Users/chris/stack.yaml':
Aeson exception:
Error in $: failed to parse field 'resolver': key "resolver" not present
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```

**Comment by chrisdone** [comment]
The problem is that stack is supposed to run also when you work on any random .hs file, aka the "global" project. I use this all the time. 

I think in your case, you'd perhaps prefer a whitelist of projects. The opposite operation to #285, which suggests a blacklist. I can implement that too. Then you would do something like:

``` lisp
(add-hook 'haskell-mode-hook 'intero-mode-whitelisted)
```

**Comment by chrisdone** [comment]
@anderspapitto I've added whitelist support. Please check out this: https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects Now you can tell Intero where it's wanted, either by specifying project individual directories, or a whole `/home/me/projects` parent directory.

**Comment by anderspapitto** [comment]
thanks chris! I've actually gone with a slightly different variant

```
(use-package intero
  :init
  (defun intero-mode-unless-global-project ()
    "Run intero-mode iff we're in a project with a stack.yaml"
    (interactive)
    (unless (string-match-p
             (regexp-quote ".stack/global-project")
             (shell-command-to-string "stack path --project-root --verbosity silent"))
      (intero-mode)))
  (add-hook 'haskell-mode-hook 'intero-mode-unless-global-project))
```

this leans on the `stack` executable to figure out if I'm in a stack-supporting project or not, so I don't have to maintain any explicit lists.

**Comment by chrissound** [comment]
Does anyone know how I could use this in spacemacs? I'm not too sure where in my .spacemacs file I can insert the above code.

**Comment by PierreR** [comment]
@chrissound Did you manage it in `spacemacs` ?

I have been trying to get black/withlisting in `spacemacs` without success so far. For instance I am replacing [intero-mode](https://github.com/syl20bnr/spacemacs/blob/master/layers/%2Blang/haskell/funcs.el#L53) with
```
  (setq intero-whitelist '("/home/vagrant/projects/"))
  (intero-mode-whitelist)
```
PS: I had to manually change the `autoload.el` so that emacs recognize `intero-mode-whitelist` function.

Everything works excepts `intero` seems to totally ignores the whitelist or blacklist variable. I have been trying to move the `setq` definition around but no luck.

**Comment by PierreR** [comment]
If it helps there is actually a difference when I change the line `(intero-mode)` into `(intero-mode-whitelist)`. 

In the first case, `intero` would fail to boot at spacemacs start up time because it tries to do so on the `recentf-files` (including for instance `~/.xmonad/xmonad.hs`).  

In the second case, `intero` does not fail at startup but only when I try to edit the file.

**Comment by chrissound** [comment]
Didn't attempt going  further with this @PierreR. If you get it working though - I'd be keen to have a look!

**Comment by peterbecich** [comment]
This warning appears for me while using Eshell over TRAMP.  The remote machine does not have Stack installed and has no Stack projects on it.  I'm using the whitelist but nevertheless it seems Intero is attempting to find a Stack project on this remote machine.  Dired over TRAMP doesn't trigger the warning, though.
