### ISSUE TITLE
Obscurity of indirect module failures

### ISSUE THREAD

**Issue by deepfire** [commercialhaskell/intero#363]
Currently intero will not directly indicate it that a module cannot be loaded because of some issue external to that module -- no flycheck popups would appear and no error status would be indicated.

Only when `intero-repl-load` is invoked, this kind of module-external failures will be shown to the user.

`haskell-mode` used to signal non-local errors using an error overlay at the first line of the file.

**Comment by chrisdone** [comment]
It's because flycheck won't show errors from other buffers. Intero does provide the information to flycheck.

But flycheck might support errors from other modules soon. My fork of it already supports it, but they dilly daddled about merging it and I ran out of energy on it. It seems someone else has taken up the task and getting it merged, so you might be in for a treat!

Add yourself as a watcher to this PR: https://github.com/flycheck/flycheck/pull/1191

**Comment by deepfire** [comment]
Thank you!
