### ISSUE TITLE
Intero jumps to wrong source file from REPL errors

### ISSUE THREAD

**Issue by jaseemabid** [commercialhaskell/intero#382]
Compilation errors are reported on some temporary file (like `~foo/.stack-work/intero/intero19083YEF.hs:150:17`) rather than the actual source, making it hard to jump back to source from repl.

**Comment by purcell** [comment]
Thanks for the report. What would be the steps to reproduce this?

**Comment by jaseemabid** [comment]
Steps to reproduce. 

1. Compile a source file with `intero-repl-load`
2. REPL buffer shows errors
3. The file reported is always `<project>/.stack-work/intero/intero<some id>.hs` instead of source file

**Comment by purcell** [comment]
Thanks. I committed a fix for this in 5396b41. It's a bit magical, because it processes the repl output to reflect the original file name, so if @chrisdone would prefer a different approach I'm happy to rework it. (It's easy enough to leave the REPL displaying the temp file path in the error message, and have the click target go to the right location, but I figure my committed solution is a nicer user experience and merits the magic.)

**Comment by jaseemabid** [comment]
@purcell Awesome. I'll update and test this out.

**Comment by purcell** [comment]
@jaseemabid Everything working for you now, then? :-)

**Comment by jaseemabid** [comment]
@purcell The data is correct.

I could jump to source by pressing enter on the error, which is missing now. The files are not hyper links anymore.

**Comment by purcell** [comment]
> I could jump to source by pressing enter on the error, which is missing now. The files are not hyper links anymore.

They already weren't hyperlinks for me, so I think there must have been something separate going on: I don't think this change broke it. :-/
