### ISSUE TITLE
Feature request: better completion in (Haddock) comments.

### ISSUE THREAD

**Issue by ntc2** [commercialhaskell/intero#392]
I would like better completion in comments, both Haddock and non-Haddock.

First, a really easy one: the default `company` configuration in `intero` completes identifiers to lowercase in comments. E.g. completing at `<complete here>` in
``` haskell
fooBar :: ...

-- | Adds baz functionality to 'foo<complete here>
fooBarBaz :: ...
```
results in the completion `foobarbaz`, instead of `fooBarBaz`. A solution is to add
``` elisp
(setq-local company-dabbrev-downcase nil)
```
to your `intero-mode-hook`; **I suggest making this the default** and letting users override it if they prefer the downcasing behavior.

Second, a harder one: the completions in comments do "dumb" completion based on strings available in the current file, but it would be better to do "smart" completions when completing after `'` or `@` (for code in Haddock comments). For example, right now I can't complete imported names in a Haddock comment.

**Comment by purcell** [comment]
Yeah, I don't think it would be appropriate for us to override the behaviour of _other_ company backends in the `intero` code. But you're right that `haskell-mode` users might like to add that setting to their configs.

Great point otherwise: I guess the current completion code only triggers when there's a symbol at point, and that's generally not true inside a comment. I can see that it would be useful to address that.

**Comment by gracjan** [comment]
For what it is worth `haskell-mode` sets `dabbrev` variables:

```
  (setq-local dabbrev-case-fold-search nil)
  (setq-local dabbrev-case-distinction nil)
  (setq-local dabbrev-case-replace nil)
```
Why `company` backend does not honor those is a mystery.

**Comment by purcell** [comment]
`company` appears to have its own equivalent variables: `company-dabbrev-ignore-case` `company-dabbrev-downcase`, so perhaps just customize those. (I still don't believe that `haskell-mode` should override any of these vars.)

**Comment by ntc2** [comment]
@purcell, why do you think `haskell-mode` should avoid overriding these
`company` defaults *locally* to `haskell-mode`? The defaults give the wrong
behavior in haddock comments.

**Comment by purcell** [comment]
The `dabbrev` company completion backend is something that you happen to have enabled, and you're using it in `haskell-mode`. You've found the behaviour of that backend is not what you want, for the haddock-specific use case, but that doesn't mean your preferences are universal. Fortunately it's easy to add your own modified settings to `haskell-mode-hook`: indeed, that's how elisp packages are supposed to be configured, rather than making super-packages that try to cover every user's needs.

If `haskell-mode` overrode the defaults, then somebody else might get frustrated or confused. In general, it's hostile for packages to impose configuration on unrelated code, unless it is directly necessary for them to function properly.

**Comment by purcell** [comment]
A further point is that `haskell-mode` (quite rightly) doesn't even depend on `company`, since the latter is an optional package that may or may not be used in a user's emacs configuration. So adding `company`-related code to `haskell-mode` will cause byte-compilation warnings for many, and also increases the maintenance burden.

**Comment by gracjan** [comment]
There is this usual problem where to put pieces of code/data/configuration that is just in between two packages. We can either arbitrarily decide that one package will take care of it, or we can decide to delegate responsibility to a global bag of configurations like Spacemacs or just drop it on users while writing copious amount of documentation how to make haskell-mode work well with company mode.

In this case we know what the values for options is as Haskell is case sensitive language, period. No user preferences and opinions come to the picture. I think that dropping configuration burden on users not acceptable. Forcing them to install Spacemacs just to make haskell-mode work with company is also disturbing. Making them write a tutorial or read one is also problematic.

That leaves as with one option: recognize that company mode is a more established package and use haskell-mode to preconfigure company so that it Just Works.

**Comment by ntc2** [comment]
@purcell, thanks for explaining your reasoning. It sounds like the source of the disagreement could be conflating `haskell-mode` with `intero`: I'm proposing to add this default `company-dabbrev-downcase` setting to *`intero`*, not to `haskell-mode`. It's certainly the case that, unlike `haskell-mode`, `intero`  does depend on `company-mode`

https://github.com/commercialhaskell/intero/blob/dc8491abf3ced70a1dcb588fe5e8376fb8180719/elisp/intero.el#L16

and the `dabbrev` backend seems to be enabled automatically, since I have no config related to it (except the one I'm proposing of course).

I agree with @gracjan that this should "just work", and that the defaults are wrong, I also agree with you that `haskell-mode` is probably not the right place for this default [1]. But `intero` should set this default up, since it brought in `company` (which brought in `dabbrev`).

The more general issue of intelligent completion inside `@` and `'` in comments would remain, and should probably be a different `intero` issue.

[1] On the other hand, it would be nice if users using `haskell-mode` and `company` without `intero` didn't have to worry about this, and so setting it in `haskell-mode` would be nice for those users. I agree that warnings related to `company` not being available are no good, but perhaps there is some elisp technique for making the setting conditional on `company` being available? I don't know much elisp ...

**Comment by purcell** [comment]
Thanks guys. Yeah, I can definitely see both sides of the argument. I'm absolutely against preconfiguring `company` in `haskell-mode` (which is already an overly-complex monolithic package), but would be open to applying `company` tweaks via `intero`.

However, having looked at the `company` code a bit, I think we're all going off the deep end talking about how to override its behaviour here: it turns out that `company` already has has some special handling for `haskell-mode`.

Specifically, there's a `company-dabbrev-code` backend, which is a sane version of `company-dabbrev` for use in code buffers. It's even enabled by default ahead of `company-dabbrev`! So let's figure out why we're getting unwanted `company-dabbrev` results here in the first place. The right fix might even end up being in `company` itself.

**Comment by gracjan** [comment]
Actually the situation is even better. ` company-dabbrev-downcase` defaults to `'case-replace` and that means to use the value of `case-replace`. This one is standard and we can safely because Haskell is defined as case sensitive language.
