### ISSUE TITLE
intero fails to setup with ghc > 8.0.2 -- how to upgrade intero?

### ISSUE THREAD

**Issue by damiencourousse** [commercialhaskell/intero#413]
Hello,

Possible duplicate of #330, but not sure.

Intero fails to setup when using LTS with ghc-8.0.2.  The problem occurs at least with lts-8.11 and lts-8.12.

I don't know why intero tries to setup version 0.1.13 and not a newer version.

Steps to reproduce:
```
$ stack new --resolver lts-8.11 temp
$ cd temp
$ stack exec ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2
$ emacs Setup.hs
```

Intero then reports this error message in emacs, in the Messages buffer:
```
Intero is not installed in the Stack environment.

Installing intero-0.1.13 automatically ...

While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      ghc: needed (>=7.8 && <8.0.2), 8.0.2 found
    needed for package intero-0.1.13
Could not install Intero!

We don't know why it failed. Please read the above output and try
installing manually. If that doesn't work, report this as a
problem.
``` 

Other relevant information:
```
$ emacs --version
GNU Emacs 24.5.1
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```

Thank you,
Damien

**Comment by damiencourousse** [comment]
OK the issue is solved for me:
a local version of `intero-0.1.13` was installed in `~/.emacs.d/elpa`.
Deleted it, restarted emacs in the Haskell source tree of my `temp` project, and `intero-0.1.20` was automatically installed.

I am leaving the issue opened though, because as a noob user of intero, I am not sure if intero should have automatically upgraded itself, and what is the procedure to upgrade intero.

BTW, thank you for this very nice tool!! :)

**Comment by chrisdone** [comment]
Intero should not be installed anywhere except by the mode itself.

**Comment by nwg** [comment]
I had this problem today. 

--
Error: While constructing the build plan, the following exceptions were encountered:                                   
                                                                                                                       
In the dependencies for intero-0.1.34:                                                                                 
    ghc-8.6.3 from stack configuration does not match >=7.8 && <=8.6.1  (latest matching version                       
              is 8.6.1)                                                                                                
needed since intero is a build target.                                                                                 
--

I have not installed intero using any method except through the mode. It should be noted that intero-0.1.35 is on hackage.

I am using stack lts-13.0 and thus ghc 8.6.3 . I can not get intero to correctly update itself unless i wipe out my ~/.emacs.d/elpa/intero-20181109.1547 . If i do this, then intero automatically updates itself and everything works.

So the gist of my problem is that auto updating didn't work, but wiping out the ~/.emacs.d/elpa//intero-20181109.1547 folder did allow me to upgrade, and after upgrade my elpa dir was ~/.emacs.d/elpa/intero-20181224.1911/ , which is newer than intero-0.1.34 and thus supports the newer ghc. So there is some kind of inconsistency between a regular autoupdate and the wiping/reinstalling.

**Comment by damiencourousse** [comment]
I also experienced exactly the same problem when moving to lts-13.0.
I used the following workaroud: I forced intero version 0.1.35 with this declaration in my emacs config:
```
'(intero-package-version "0.1.35")
```

**Comment by damiencourousse** [comment]
> Intero should not be installed anywhere except by the mode itself.

@chrisdone  do you mean that we should make sure that intero is **not** installed, say, in `$HOME/.local/bin`, as it would be with `stack install intero`?
Where does the mode install intero? (expecting it to be installed in `~/.emacs.d`, but I might be wrong).

**Comment by damiencourousse** [comment]
Did a new check, which reproduces the issue:
- removed the declaration `'(intero-package-version "0.1.35")` in my emacs config
- made sure intero is only found in `~/.emacs.d`, and not in `~/.local/bin`:
```
$ ~/.emacs.d(master)        
✓✓✓$ find -iname '*intero*'
./elpa/intero-20181109.1547
./elpa/intero-20181109.1547/intero.el
./elpa/intero-20181109.1547/intero-autoloads.el
./elpa/intero-20181109.1547/intero.elc
./elpa/intero-20181109.1547/intero-pkg.el
```

With this configuration, I got exactly the error as reported by @nwg.

Then,
Wiping out the files in `.emacs.d` forces a fresh install of version `0.1.35`.

So we have at least two ways to workaround this issue:

1. wiping out the files in `~/.emacs.d`,
2. force intero version with a declaration in the emacs config.

But for me the issue still persists each time I need to upgrade to a new version of intero.

@chrisdone I would be glad to help, but not sure how.  Feel free to ask, if need be!
thanks,
