### ISSUE TITLE
Unable to send individual line to REPL

### ISSUE THREAD

**Issue by paullucas** [commercialhaskell/intero#417]
I was very surprised that this function didn't exist. Here's my current (hacky) solution. 

```
(defun intero-find-repl ()
  (car
   (cl-remove-if-not (lambda (-buf)
                       (string-match "*intero:\\(.+\\):repl" (format "%s" -buf)))
                     (buffer-list))))

(defun intero-send-command ()
  (interactive)
  (comint-send-string (intero-find-repl)
                      (concat (buffer-substring (line-beginning-position)
                                                (line-end-position))
                              "\n")))

(eval-after-load "haskell-mode" '(define-key haskell-mode-map (kbd "C-c C-c") 'intero-send-command))
```

**Comment by purcell** [comment]
I'm not personally convinced that this workflow is super useful, since generally a given line (or region) in a haskell-mode buffer will not be happily evaluated in isolation in the REPL.

But I've taken this as an opportunity to tidy up `intero-repl-load`, and I've added `intero-repl-eval-region` in order to provide the requested functionality anyway, bound to `C-c C-c`. If you select a region and hit `C-c C-c`, it'll be sent to the repl (which will be started if necessary). And if there's no region selected, the current line will be sent.
