### ISSUE TITLE
Lazy loading proposal

### ISSUE THREAD

**Issue by s9gf4ult** [commercialhaskell/intero#431]
Now if you open `.hs` file and `intero` is enabled in your `init.el` then emacs starts binary `intero` immediately even if you do not need it. This is not the problem by itself, but if you have `desktop` enabled and work with many projects then every restart of emacs becomes very painfull: emacs loads `intero` on each file it opens and it is not just slow, it also consumes all the RAM because of tonns of `intero` processes starting while loading files. 

I have desktop with 16Gb of RAM and it is not enough to just restart emacs. It also takes about 2-3 minutes to just load emacs and reopen all files, after what I open `htop` and kill all the started `intero` processes to free my RAM. This is extremely annoying. Hopefully I restart emacs approximately once a month.

The point is to load process `intero` lazily and defer loading until it is really needed or `intero-restart` is called. I hope it is simple to implement and solve many performance problems with intero.

**Comment by chrisbarrett** [comment]
Any reason can't add the commands you care about to `haskell-mode-map` and autoload them?

**Comment by s9gf4ult** [comment]
@chrisbarrett I did not understand, how adding `intero` the mode to `haskell-mode-map` can help to not load `intero` the program?

**Comment by chrisbarrett** [comment]
Caveat: I'm not an intero contributor, just a github issues lurker, so I'm making some assumptions about how things work.

Rather than using `intero-global-mode`, you should be able to enable `intero-mode` for specific buffers as you need it.

Additionally, you could add some of the intero commands to `haskell-mode-map`, so that you can call them even if `intero-mode` isn't active. You might have to add some elisp before-advices to get intero to start.

Here's some totally untested elisp: 
```lisp
(defconst my-config--haskell-mode-intero-commands
  '(("C-c C-t" . intero-type-at)
    ("C-c C-i" . intero-info)
    ("M-." . intero-goto-definition)
    ("C-c C-l" . intero-repl-load)
    ("C-c C-c" . intero-repl-eval-region)
    ("C-c C-z" . intero-repl)
    ("C-c C-r" . intero-apply-suggestions)
    ("C-c C-e" . intero-expand-splice-at-point)))

(defun my-config--enable-intero (&rest _)
  (when (derived-mode-p 'haskell-mode)
    (unless (bound-and-true-p intero-mode)
      (intero-mode +1))))

(with-eval-after-load 'haskell-mode
  (dolist (it my-config--haskell-mode-intero-commands)
    (let ((cmd (car it))
          (key (cdr it)))
      (define-key haskell-mode-map (kbd key) cmd)
      (advice-add cmd :before #'my-config--enable-intero))))
```

**Comment by kRITZCREEK** [comment]
It also sounds like your exact use-case is covered by intero white/blacklists? https://github.com/commercialhaskell/intero#whitelistingblacklisting-projects

**Comment by purcell** [comment]
I think that - in principle - `intero` *is* lazy-loaded, but the issue here is that when files are re-opened by `desktop.el` etc., there is an initial `flycheck` pass which triggers `intero` to be initialized. So this makes me wonder if `flycheck` could be performed lazily, according to whether files are actually being displayed in a visible buffer. If *that* problem were solved, there would be a wider benefit.

**Comment by s9gf4ult** [comment]
@purcell yes, I think you are right. Do you know how to make `flycheck` check files on demand?

**Comment by purcell** [comment]
I see that flycheck has a variable called `flycheck-check-syntax-automatically`, so you could try changing the default of that in your init file before invoking desktop.el:

```el
(with-eval-after-load 'flycheck
  (setq flycheck-check-syntax-automatically
        (delq 'mode-enabled flycheck-check-syntax-automatically)))
```

**Comment by purcell** [comment]
Note that this would simply tell flycheck to never make an initial check: you'd then have to trigger a check by modifying or changing the buffer. So what you'd need to enable lazy checking would be some further code in `focus-in-hook` or `window-configuration-change-hook` that would force that initial check in newly-visible buffers.

**Comment by purcell** [comment]
There's actually some code in Flycheck itself for this sort of deferred-until-visible checking, and it explicitly defers the initial check upon its `mode-enabled` event. So I'm really not sure what's going on here.
