### ISSUE TITLE
Flycheck cannot use this syntax checker for this buffer

### ISSUE THREAD

**Issue by manuel-uberti** [commercialhaskell/intero#448]
Hi,

I have `intero` set up like this in my `init.el`:
```
(use-package intero                     ; Development mode for Haskell
  :ensure t
  :mode ("\\.hs\\'" . intero-mode)
  :config (add-hook 'haskell-mode-hook 'intero-mode))
```
I created a project using `stack` like this:
```
stack new hello-world simple
```
When I try to open `Main.hs` I get this buffer popping up:
```
Syntax checker in buffer Main.hs in fundamental-mode:

  intero
    - major mode: `fundamental-mode' not supported
    - may enable: yes
    - predicate:  t

Flycheck cannot use this syntax checker for this buffer.

Flycheck Mode is disabled.  Use C-u M-x flycheck-disable-checker to enable
disabled checkers.

--------------------

Flycheck version: 31snapshot (package: 20170714.948)
Emacs version:    26.0.50
System:           x86_64-debian-linux-gnu
Window system:    x
```
I am using GNU Emacs `26.0.50 (build 1, x86_64-debian-linux-gnu, GTK+ Version 3.18.9) of 2017-07-14`.

If you need other information or you need me to do other tests, feel free to ask.

**Comment by purcell** [comment]
Your 'mode' association in the above snippet is wrong: `intero-mode` is not a major mode, so you should associate `.hs` files with `haskell-mode` instead. This should happen by default when `haskell-mode` is installed.

Also, rather than adding `intero-mode` to `haskell-mode-hook` unconditionally, consider simply enabling `intero-global-mode`.

**Comment by manuel-uberti** [comment]
Thank you.

As for the hook, I followed these guidelines: https://commercialhaskell.github.io/intero/
