### ISSUE TITLE
Intero 1.23 has problems loading current file

### ISSUE THREAD

**Issue by emaphis** [commercialhaskell/intero#473]
This is on a Windows 10 32 bit system.
Intero 0.1.23 doesn't seem to load the current file any more

Upgrading to Stackage LTS-9.4 upgrades Intero 0.1.23 after I upgraded Emacs' Intero-mode from Melpa.

Now Intero doesn't seem to load current file. Fly-check doesn't highlight the types of values in the project, C-c C-t claims whatever value I query isn't in scope: "<interactive>:1:1: error: Variable not in scope: add6"
Values from the Prelude work fine, and also show up in company completion

After I load the project, Intero 0.1.21 shows 89 Meg of memory usage while Intero 0.1.24 shows 64 Meg. I would try to load a file into the Intero process manually to see if that works, but I haven't figured out how yet.

**Comment by chrisdone** [comment]
Try updating your Elisp?

**Comment by bmjames** [comment]
I've had similar problems on a Windows 7 64-bit system. (A colleague on a similar system doesn't seem to have the problem, though.)

The cause was that when emacs sent the `:move` command to the intero process, the file path arguments were appearing with unescaped `\` separators, causing the move to fail, so the temp files used for checking were empty.

My current workaround is hacking a fix into `intero.el`, to replace `\` with `/` before formatting the move command.

**Comment by FrodoKenny** [comment]
Same issue here, following bmjames I solved it by changing line 667:

(format ":move \"%s\" \"%s\"" -> (format ":move %S %S"

**Comment by chrisdone** [comment]
Ah, fair enough. I'll apply that change.

**Comment by chrisdone** [comment]
Please let me know if you have further issues!
