### ISSUE TITLE
"Couldn't guess that module name." error in Vs-code and Haskero

### ISSUE THREAD

**Issue by deflexor** [commercialhaskell/intero#476]
If source file compiles with errors then type signature doesn't work, intead type
definitions of everything in this file look like:
`foldl Couldn't guess that module name. Does it exist?`

**Comment by CaptJakk** [comment]
This is extremely aggravating. I am having the same issue.

**Comment by purcell** [comment]
> If source file compiles with errors then type signature doesn't work

I can understand that this is frustrating, but the above could be re-phrased as "when the Haskell compiler cannot figure out the types of my definitions, `intero` won't tell me their types." In other words, if you understand that Intero is delegating this understanding of the code to GHCi, then this is the expected result by default. :-)

So there are hard limits on what `intero` can do to help. Let's consider a couple of options.

In the case where the code is well-formed but not well-typed, `intero` would theoretically be able to re-run compilation with `-fdefer-type-errors`, which would allow it to return _some_ types at the expense of a lot of extra compilation, latency and complexity.

Alternatively, `intero` could run "green"/"blue" backends, and return type information from the backend in which the file had last compiled cleanly. You can imagine how quickly this info could get out of sync with the edited file, though, and also how much complexity this approach would add.

So I don't want to answer on behalf of all the other `intero` maintainers, but IMO this is extremely unlikely to get "fixed".

**Comment by chrisdone** [comment]
There's actually something possibly more hopeful and reliable possible today! ☝️ 😄 

Previously `-fdefer-type-errors` was impractical because it classed all type errors as warnings, without a way to differentiate. 

On GHC 8, they changed their error messaging system so that it became possible to differentiate these, but I was waiting a while for GHC 8 to become established before taking advantage of this fact. Now that it's more available, we, I believe, could enable `-fdefer-type-errors` on Intero start up.

![screenflow](https://user-images.githubusercontent.com/11019/33479994-1ea9a7ee-d687-11e7-8bce-672baf225801.gif)

Your editor (in this case Emacs is already setup to do it [here](https://github.com/commercialhaskell/intero/blob/648903c6d82b061bcc55dbed67f7f585027613b9/elisp/intero.el#L740..L742), which you can ask the maintainers of Haskero or Vs-Code to implement to recognize these warnings as errors, and enable `-fdefer-type-errors` when you start the project. I suggest opening an issue to them linking to here.

I'll open a separate issue/PR for the Emacs Lisp binding. It probably needs to be trialled by someone for a day. I don't mind trialling it.

**Comment by chrisdone** [comment]
See further discussion here: https://github.com/commercialhaskell/intero/pull/495
