### ISSUE TITLE
Automatic import management

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/intero#48]
This comes in many forms:
- [ ] Providing a keybinding to import a thing which automatically inserts that into the import list and sorts the import list.
- [ ] Providing completion for choosing modules from:
  - [ ] The current project.
  - [ ] The dependencies of the current project.
  - [ ] All packages installed in the current resolver.
  - [ ] All packages available in the resolver.
- [ ] Automatically adding imports when GHC reports that an identifier isn't in scope:
  - [ ] We can hoogle for this, once `stack hoogle` is merged.
  - [ ] We can hunt through the current project via the `Intero` backend.
- [x] Automatically removing imports when no longer necessary. GHC warns us about this. If the user turns off that warning, we don't do the auto-removing.
- [ ] Possibly provide "explicit" imports functionality -- only things used.

Anything that automatically removes something should prompt, but in a benign non-focusing-stealing way. We may simply hook into `flycheck` with some cleverness.

**Comment by mboes** [comment]
FWIW https://github.com/juiko/company-ghci supports the import completion part of this ticket. Maybe possible to steal some code?

**Comment by chrisdone** [comment]
For completing module names at an import statement, yeah, I could steal more code.

I was thinking rather, instead of jumping to the import list from where you're writing your code, hitting a key binding like `C-i` which prompts for clever Haskell-module-specific completion, and inserts the module in your import list for you, with your typical choice of import style. Like this:

![out](https://cloud.githubusercontent.com/assets/11019/15799125/9637137e-2a52-11e6-8956-861e9f4208c6.gif)

That's something I have locally in my .emacs config, didn't push it anywhere yet, as its completion is just based on modules I've used in the past (oddly, this is a fairly robust way to get module completion, but more "legit" sources are desirable).

**Comment by mboes** [comment]
Sounds great to me. It would subsume (and therefore make unnecessary) the company completion I guess. Though often I find myself in a situation where the import statement is already there, it's just that I want to modify it. Would the ido-like stuff work in that case too? In that particular case the company completion is straightforward enough: if I have `import Data.ByteString` and I want to change that to `import Data.ByteString.Lazy`, it'll complete "Lazy" the moment I press ".".

**Comment by chrisdone** [comment]
Agree completely, when you're already at an import, you might as well use the existing completion infrastructure for that case.

**Comment by chrisdone** [comment]
Automatic removal of imports has been implemented as part of the suggestions framework via GHC's redundant import messages.

**Comment by MichaelXavier** [comment]
If you're looking for good examples for item 1 (Providing a keybinding to import a thing which automatically inserts that into the import list and sorts the import list), you may want to look to Purescript's psc-ide-mode. I think probably the majority of the feature is actually implemented in the psc-ide server. This has become the standard workflow (at least for me) in Purescript and it works really well:

* Split the window between your code and flycheck. Start coding.
* Flycheck will mark undefined bindings as errors. This is common in a lot of projects that you'll use something before thinking to import it. Doubly so in Purescript which provides much less code implicitly than Haskell.
* Move point to the token that's missing and do C-c C-i.
* Minibuffer will ask you which module to import the token from. Tab completion seems to scan the available modules for ones that export the token. It may default if there's only one, not sure.
* When you choose a module, it adds it to the imports stanza if its not there, and if it is, adds the token to the explicit imports list in a sorted fashion.
* `C-c ! n` to move to the next flycheck error and repeat.

I think this is probably why most Purescript code tends to have very precise imports: either by qualified import or by explicit binding imports. Its possible special consideration should be made for Haskell which is a bit different, but a gentle nudge towards precise imports may be a good idea!

**Comment by acowley** [comment]
I think this feature stalled as we sort out how to do general programmatic editing of Haskell source. Doing it with regexps in elisp is quick-to-market, so to speak, but tends to leave us with a lot of corner cases. I started a helper library/executable for doing some of these manipulations, but it does depend on `haskell-src-exts`. It's a very slow-to-compile dependency that I don't think is yet in intero's transitive dependency set, and is also problematic because it undergoes breaking changes rather frequently meaning that the versions in different stackage package sets would not all work. Point is, we'd all have to hold hands and jump into that if it is to become a part of intero. Alternately, we could keep it as a separate executable that would effectively provide a set of optional features for intero.

Implementation aside, a question I ran into when playing with the prototype is that I don't know how to handle importing of things like data constructors. Say you're pattern matching on a data type, `Foo`. Manually, you might write `import SomeLib (Foo(..))`. But that `Foo(..)` import is the result of considering multiple locations in your code. Is it okay if we never generate that kind of import syntax? Or should the UI be more interactive, so you'd have point at `Foo` and, when asking to import it, ask what methods or constructors to import?

My current view is that we should generate dumb syntax and let an auto-formatter clean everything up as a separate pass, in which case bringing `hindent` into the fold becomes a more immediate concern.

**Comment by kRITZCREEK** [comment]
@acowley we recently changed the behaviour with regards to data constructors to always use `(..)` if at least one data constructor is imported. A bit of discussion can be found here: https://github.com/purescript/purescript/pull/2413

**Comment by acowley** [comment]
Thanks @kRITZCREEK! Why is there "no benefit to being specific with constructors"? I can't say I have strong feelings on this, but the obvious benefits are:
- Avoid name collisions
- Make it clear to a reader where a name came from

Perhaps things are different in PS. Using `(..)` is probably the easiest solution, so I wouldn't fight it.

**Comment by kRITZCREEK** [comment]
The primary reason for the PureScript compiler warning on implicit imports is to allow for purely additive API changes to not require a major (breaking) version bump. Adding a data constructor to a type is always a breaking change, as pattern matches might become partial, and so data constructors can be imported implicitly in PureScript.

I definitely think there is value in being explicit about data constructors as well, as it allows for easy tracing of identifiers in non-ide situations. For the API/SemVer reason it is not necessary for data constructors to be explicit so that's where we drew the line in PureScript. It's one more data point for you I guess :)

**Comment by i-am-the-slime** [comment]
May I ask what the status of this is?
If it fails sometimes that should still be better than not getting any help, right?

**Comment by chrisdone** [comment]
Reducing Intero's scope, closing.
