### ISSUE TITLE
Cryptic warning (error) message on finding stack executable

### ISSUE THREAD

**Issue by rimbaudcode** [commercialhaskell/intero#501]
I'm getting the following warning (error?) message when using intero:

`It's worth checking that the correct stack executable is being
found on your path, or has been set via
intero-stack-executable. The executable being used now is:

/Users/rmbd/.local/bin/stack

WHAT TO DO NEXT

If you fixed the problem, just kill this buffer, Intero will make
a fresh one and attempt to start the process automatically as
soon as you start editing code again.

If you are unable to fix the problem, just leave this buffer
around in Emacs and Intero will not attempt to start the process
anymore.

You can always run M-x intero-restart to make it try again.`

Now, if I check the path for stack, I get `/Users/rmbd/.local/bin/stack`, which matches what intero finds. So, what's going on? I have only one stack installed and reachable. Intero finds it. But then, when I kill the buffer or restart intero, the warning (error) buffer doesn't go away. 

My main issue is that I don't know what to fix. The message says that I should fix _the_ problem. However, _a_ problem is never found. I'm only informed that 'it's worth checking' stack's path.

Thanks for any pointer on what to fix!

**Comment by acowley** [comment]
Usually when this happens to me, it turns out a `stack build` of the project has some issue with a dependency. After that, I make sure `stack build intero` in the directory with the `stack.yaml` I’m working with is successful. Do either of those shed any light on the situation?

**Comment by rimbaudcode** [comment]
Hi. Thanks for the reply. I found the issue: I'm having troubles with stack building projects with the lts-10.0 resolver. Intero was trying to start stack locally, but it couldn't, so it felt into the global stack and that triggered the warning message in emacs. But, when I start a project using a different resolver (one that builds projects in the shell), the warning (error) message is gone and intero works smoothly. However, I still think the message is a bit unhelpful since it does not point to possible causes, right?

**Comment by acowley** [comment]
You're right. The problem is that this message is just a shot in the dark at what typically goes wrong, and I think this has drifted slightly over time. In the past, there was a very common problem of people updating `stack`, but then it not being at the front of their `$PATH`, so Intero telling you about which `stack` it was using was playing the odds. These days, most of the time I see these error messages it is because a `.dir-locals.el` was not picked up for some reason, and the wrong `stack.yaml` (perhaps the global one) is being used.

So maybe the emphasis of this error message should be on which `stack.yaml` is used, and maybe even what resolver it specifies? Either way, this is only shown when things have gone totally sideways, so I doubt we can achieve perfection in diagnosing the problem. I too read the current message as emphasizing which `stack` is used, which is very seldom my problem, but I don't know how representative my experiences are.

**Comment by rimbaudcode** [comment]
Oh. I see your point: it's difficult sometimes to find out what's going on when hitting an error in emacs.
 
On the other hand, I agree, maybe the error message should point to check which `stack.yaml` is being used, but perhaps also to check the `$PATH`, or, what helped me, and you already mentioned, to run `stack build` and see.

Thanks for the help!
