### ISSUE TITLE
Djinn with in-scope terms

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/intero#8]
http://www.reddit.com/r/haskell/comments/2qljmg/how_to_do_exploratory_programming/cn7cat4

This is pure fantasy, but would be incredible if it could happen. Limit yourself to what's in scope, sprinkle some heuristics on top, could be tractable.

Edit: I realize this is tantamount to bolting a proof assistant on, but I think there's an 80/20 solution to be found here that could help in type-tetris'y situations.

**Comment by chrisdone** [comment]
Going back to the drawing board, but might come back to this idea later.

**Comment by chrisdone** [comment]
A reddit post reminded me:

I started work on adding Djinn to Intero, so that it could query on all data types, classes and functions in scope on this branch: https://github.com/commercialhaskell/intero/compare/djinn?expand=1#diff-a469118375854c9ae9408cbd3bb03b39R1732

But lost the will to go on. The GHC "API" is really an up-hill struggle, I'm pretty stubborn but I can't stand working with it anymore.

If anyone else wants this, they can pick up the patch: you need to provide the constructor slot types on the line I highlighted, and then Djinn (and thus `:djinn`) will be aware of all the data types in the "current" module. Likewise the `AnId` case can be used to provide types of functions in scope, and `isClassTyCon` for classes. I'll provide any guidance if I can to anyone with the time/energy to try it.

**Comment by ChShersh** [comment]
Consider using [`exference`](https://github.com/lspitzner/exference) instead of Djinn. Looks like it's a more advanced tool.

**Comment by chrisdone** [comment]
Not going to implement this, closing.
