### ISSUE TITLE
Can take a long time to open a file

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/intero#94]
When I open a file in a large project, it can take 20 seconds or more to open, due to starting intero.  Is it possible to do this async?

**Comment by mgsloan** [comment]
With company-mode autocomplete + flycheck, it seems that I cannot really avoid the 20 second editor freeze.  If I ctrl-g during load, then the buffer does not appear, however it does now exist so I can switch to it.  However, as soon as I start typing, it needs to start intero.

**Comment by chrisdone** [comment]
Starting intero or installing it?

**Comment by Blaisorblade** [comment]
I have similar issues too, just for starting intero after installation.

Here's how to reproduce my variant:
- check out a recent Agda with stack support (say,  https://github.com/agda/agda/commit/12d207527883ddb35512dc6423983e1c7c913d75)
- move away `.ghci`, it's setup for cabal not for stack
- `stack build`, for both `Agda`. Also build `intero` (`intero-mode` did it for me, the next steps still how the bug after install).
- open `src/full/Agda/Main.hs`
- press `C-c C-l` to open the REPL
- search in the buffer for `runTCMTop`
- press `M-.` to jump to its definition.
- *Emacs stops responding to pressing arrows.* This is an issue — `M-.` needs to trigger an asynchronous loading.
- pressing C-g works, but you see messages in the REPL buffer about *compiling* Agda to a temp folder. That's similar, `stack ghci Agda:lib` will either compile to `.stack-work` or load as interpreted (I don't get when is when).
- even now, `M-.` still takes 1-2 seconds (I feel), *almost every time* you jump to `runTCMTop` (sometimes it's instantaneous, mostly not — try repeating `M-.` and `M-*` in a loop). Given this specific intero process is using 3.2GB of memory (with stable usage), I suspect this impredictability is due to GC pauses with an almost full heap.

```
[...]
[286 of 334] Compiling Agda.TypeChecking.Rewriting ( /Users/pgiarrusso/AeroFS/Repos/agda-bluevelvet/src/full/Agda/TypeChecking/Rewriting.hs, /var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero87367JJG/Agda/TypeChecking/Rewriting.o )
[287 of 334] Compiling Agda.TypeChecking.Rules.Data ( /Users/pgiarrusso/AeroFS/Repos/agda-bluevelvet/src/full/Agda/TypeChecking/Rules/Data.hs, /var/folders/_7/hlxv4yv95x95vgnn416b4q4m0000gp/T/intero87367JJG/Agda/TypeChecking/Rules/Data.o )
[...]
```

```
stack ghci Agda:lib
```

**Comment by Blaisorblade** [comment]
In fairness, though, in-file navigation appears always quick. Only jumping to a definition in another file is the problem.

Another issue compounding this is that "nothing happening" can mean that intero is thinking or just that the symbol is defined externally, and I don't see any difference there.

Either way, I'm not quite going back to ctags quite yet :-).

Other note: this was on GHC 7.10, I hear GHC 8 might (or might not) help: https://twitter.com/a_cowley/status/741327659146346496.

**Comment by unhammer** [comment]
>  Emacs stops responding to pressing arrows. This is an issue — M-. needs to trigger an asynchronous loading.

ycmd.el (for C++ etc.) does this, but I don't feel it's a good idea. When I press `M-.`, I really don't want to be able to move around, since then if it actually does take a bit of time, I get tricked into thinking I can move there manually, and suddenly I'm yanked into a different place. Or I press `M-.' several times out of frustration, and am yanked away many times in a row. I would rather have to manually cancel with a `C-g` so movements are predictable.

**Comment by Blaisorblade** [comment]
> When I press M-., I really don't want to be able to move around

Fair point, let me amend. That doesn't mean the whole Emacs should freeze because it's running a script, so the loading should still be asynchronous, so that other actions (even in other buffers) work fine. Then I agree that maybe moving around should fail—and should then tell me that there's a "definition search in progress" and give some option to abort.

**Comment by chrisdone** [comment]
I think it's because of running `stack --path`. I haven't confirmed that, but that's the only blocking part of opening a buffer.
